# replace your_token by your token
token: 91dc188149dfaca6f94e551413024808
# Set to "y" if you activate autologin and want to hide browser
headless: y
email: monajah180@mailnest.net
password : YN&F&8^nuZNKn%
# set to y if you want to auto update strat list
get_strategies_from_marketplace: y

# strat to test. Automatically updated if get_strategies_from_marketplace is set to y
strat_ids:
- 607a0e416f10396b0be05c0a

ask_config: n
every_pairs: n
verbose: n
browser: chrome
ask_2fa: n
exchanges:
- Binance